### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by Gabri04** [xImAnton/ms-office-discord-rpc#1]
Hello, I'm somehow new to this... I can't find a file or whatever to use this. Can you help me?

**Comment by xImAnton** [comment]
Hi and sorry for late reply.

You can clone this repo, open the `office-rpc.csproj` file in Visual Studio and build it (Strg+F5).
After that you can copy a shortcut to the built executable (located in `./bin/Release/net5.0`) in your autostart folder (on windows: enter `shell:startup` in the bar at the top of the file explorer) and it should start automatically with your system.
As explained in the README, its not guranteed to work on your system.

Let me know if this helped 😉

**Comment by NoPlagiarism** [comment]
It could be nice to have first release with .exe btw

**Comment by Gabri04** [comment]
> Hi and sorry for late reply.
> 
> You can clone this repo, open the `office-rpc.csproj` file in Visual Studio and build it (Strg+F5). After that you can copy a shortcut to the built executable (located in `./bin/Release/net5.0`) in your autostart folder (on windows: enter `shell:startup` in the bar at the top of the file explorer) and it should start automatically with your system. As explained in the README, its not guranteed to work on your system.
> 
> Let me know if this helped 😉

completely forgot to answer... it helped me, thanks!

**Comment by xImAnton** [comment]
> It could be nice to have first release with .exe btw

good idea, i will do that next week
